spring:
  profiles: local
server:
  port: 8671
eureka:
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false  ##集群时设置为true
    fetch-registry: false ##集群时设置为true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
#    lease-expiration-duration-in-seconds: 15 #default 30 seconds
#    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.cloud.client.ip_address}:${spring.application.instance_id:${server.port}}
