application:
    version: 1.0
spring:
  security:
    user:
      name: keyo
      password: 123456
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mycloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
      username: root
      password:
      validation-query: select 1
  freemarker:
      enabled: true
      check-template-location: true
      suffix: .html
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
easy:
  global:
    json:
      return:
        value:
          enable: false
